kind: project
metadata:
  name: gitops-project
spec:
  functions:
  - name: gen-iris
    spec:
      kind: job
      metadata:
        name: gen-iris
        tag: ''
        project: gitops-project
      spec:
        command: ''
        args: []
        image: mlrun/ml-models
        env: []
        default_handler: ''
        entry_points:
          iris_generator:
            name: iris_generator
            doc: ''
            parameters:
            - name: context
              default: ''
            - name: format
              default: csv
            outputs:
            - default: ''
            lineno: 11
        description: ''
        build:
          functionSourceCode: IyBHZW5lcmF0ZWQgYnkgbnVjbGlvLmV4cG9ydC5OdWNsaW9FeHBvcnRlcgoKaW1wb3J0IG9zCmZyb20gc2tsZWFybi5kYXRhc2V0cyBpbXBvcnQgbG9hZF9pcmlzCmZyb20gc2tsZWFybi5tb2RlbF9zZWxlY3Rpb24gaW1wb3J0IHRyYWluX3Rlc3Rfc3BsaXQKaW1wb3J0IG51bXB5IGFzIG5wCmZyb20gc2tsZWFybi5tZXRyaWNzIGltcG9ydCBhY2N1cmFjeV9zY29yZQpmcm9tIG1scnVuLmFydGlmYWN0cyBpbXBvcnQgVGFibGVBcnRpZmFjdCwgUGxvdEFydGlmYWN0CmltcG9ydCBwYW5kYXMgYXMgcGQKCmRlZiBpcmlzX2dlbmVyYXRvcihjb250ZXh0LCBmb3JtYXQ9J2NzdicpOgogICAgaXJpcyA9IGxvYWRfaXJpcygpCiAgICBpcmlzX2RhdGFzZXQgPSBwZC5EYXRhRnJhbWUoZGF0YT1pcmlzLmRhdGEsIGNvbHVtbnM9aXJpcy5mZWF0dXJlX25hbWVzKQogICAgaXJpc19sYWJlbHMgPSBwZC5EYXRhRnJhbWUoZGF0YT1pcmlzLnRhcmdldCwgY29sdW1ucz1bJ2xhYmVsJ10pCiAgICBpcmlzX2RhdGFzZXQgPSBwZC5jb25jYXQoW2lyaXNfZGF0YXNldCwgaXJpc19sYWJlbHNdLCBheGlzPTEpCiAgICAKICAgIGNvbnRleHQubG9nZ2VyLmluZm8oJ3NhdmluZyBpcmlzIGRhdGFmcmFtZSB0byB7fScuZm9ybWF0KGNvbnRleHQuYXJ0aWZhY3RfcGF0aCkpCiAgICBjb250ZXh0LmxvZ19kYXRhc2V0KCdpcmlzX2RhdGFzZXQnLCBkZj1pcmlzX2RhdGFzZXQsIGZvcm1hdD1mb3JtYXQsIGluZGV4PUZhbHNlKQoK
          commands: []
          code_origin: https://github.com/xsqian/demo-github-actions.git#06d375eba8c79058ea7f1da6ebfc0758973c891f
        affinity: null
      verbose: false
  - url: hub://describe
    name: describe
  - url: hub://sklearn_classifier
    name: train
  - url: hub://test_classifier
    name: test
  - url: hub://model_server
    name: serving
  - url: hub://model_server_tester
    name: live_tester
  workflows:
  - name: main
    path: workflow.py
  artifacts: []
  artifact_path: v3io:///users/{{run.user}}/pipe/{{workflow.uid}}
  source: ''
  subpath: ''
  origin_url: ''
  desired_state: online
